### PR TITLE
Swift 2.0 compliance (& removes Carthage dir)

### PR DESCRIPTION
**Pull request by emaloney**
This supersedes my earlier pull request.

### CODE REVIEW

**Comment by haveahennessy** [comment]
:boom:

**Comment by emaloney** [comment]
Thanks!!!

**Comment by haveahennessy** [comment]
Pushing a tag to make this a release in one sec.

**Comment by haveahennessy** [comment]
[v0.6.0](https://github.com/haveahennessy/Chaingang/releases/tag/v0.6.0)

**Pull request merged**
